
pub const GLOBAL_STATE_SEED: &[u8] = b"GLOBAL-STATE-SEED";
pub const USER_STAKING_DATA_SEED: &[u8] = b"USER_STAKING_DATA_SEED";
pub const POOL_TOKEN_ACCOUNT_SEED: &[u8] = b"POOL_TOKEN_ACCOUNT_SEED";
