pub const GLOBAL_STATE_SEED: &[u8] = b"GLOBAL-STATE-SEED";
pub const USER_STAKING_DATA_SEED: &[u8] = b"USER_STAKING_DATA_SEED";
pub const POOL_SEED: &[u8] = b"POOL_SEED";
pub const REWARD_POOL_SEED: &[u8] = b"REWARD_POOL_SEED";
