export const GLOBAL_STATE_SEED = "GLOBAL-STATE-SEED";
export const USER_STAKING_DATA_SEED = "USER_STAKING_DATA_SEED";
export const POOL_SEED = "POOL_SEED";
export const REWARD_POOL_SEED = "REWARD_POOL_SEED";
